### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ShotDead7297** [ChampOfGamesYT/RulesUI#4]
Please update the API to 3.8.5

**Comment by champmq** [comment]
It works with 3.0.0 since pocketmine changed it that we can use 3.x.y

**Comment by ShotDead7297** [comment]
Well it doesn't work on my server

**Comment by champmq** [comment]
What is the error?

**Comment by ShotDead7297** [comment]
There is no error it's just not on the plugins list

**Comment by ShotDead7297** [comment]
Here is my server version PocketMine-MP 3.8.4 for Minecraft: Bedrock Edition v1.11.0 (protocol version 354)

**Comment by champmq** [comment]
Did you convert the plugin?

**Comment by ShotDead7297** [comment]
It works now ty but there is a error

**Comment by ShotDead7297** [comment]
01.07 07:42:46 [Server] Server thread/CRITICAL ErrorException: "Undefined variable: message" (EXCEPTION) in "plugins/RulesUI-master/src/ChampOfGames/Rules/Main" at line 61
01.07 07:42:46 [Server] Server thread/DEBUG #0 plugins/RulesUI-master/src/ChampOfGames/Rules/Main(61): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[27] Undefined variable: message, string[101] /plugins/RulesUI-master/src/ChampO, integer 61, array[4])
01.07 07:42:46 [Server] Server thread/DEBUG #1 src/pocketmine/command/PluginCommand(58): ChampOfGames\Rules\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[5] rules, array[0])
01.07 07:42:46 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(270): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[5] rules, array[0])
01.07 07:42:46 [Server] Server thread/DEBUG #3 src/pocketmine/Server(2019): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[5] rules)
01.07 07:42:46 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2231): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[5] rules)
01.07 07:42:46 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(240): pocketmine\Player->chat(string[6] /rules)
01.07 07:42:46 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
01.07 07:42:46 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.07 07:42:46 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
01.07 07:42:46 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.07 07:42:46 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3124): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.07 07:42:46 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.07 07:42:46 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 174.200.11.31 8087, object raklib\protocol\EncapsulatedPacket, integer 0)
01.07 07:42:46 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
01.07 07:42:46 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
01.07 07:42:46 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
01.07 07:42:46 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
01.07 07:42:46 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1561966966.6572)
01.07 07:42:46 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
01.07 07:42:46 [Server] Server thread/DEBUG #19 src/pocketmine/Server(1774): pocketmine\Server->start()
01.07 07:42:46 [Server] Server thread/DEBUG #20 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
01.07 07:42:46 [Server] Server thread/DEBUG #21 (1): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)

**Comment by champmq** [comment]
Download the latest version that means download it again

**Comment by ShotDead7297** [comment]
Ok

**Comment by ShotDead7297** [comment]
Fixed ty for the help
