### ISSUE TITLE
Client crash when running /rules command

### ISSUE THREAD

**Issue by xXRyzen** [ChampOfGamesYT/RulesUI#5]
Using very latest build, i client crash with following console error:

ErrorException: "Undefined variable: message" (EXCEPTION) in "plugins/RulesUI_dev-64.phar/src/ChampOfGames/Rules/Main" at line 61

Using PMMP:
PocketMine-MP 3.8.2 for Minecraft: Bedrock Edition v1.11.0 (protocol version 354)

**Comment by champmq** [comment]
Should be fixxed now.

**Comment by xXRyzen** [comment]
works. Good job! i do have further questions. i will msg u on disc. we can close this issue.

**Comment by champmq** [comment]
Okay
